import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import { Link as LinkScroll } from 'react-scroll'
import Menu from '../sideMenu'
import SideCart from '../../cart'
import { useScrollDirection } from '../../../hooks'
import { StyledHeader, StyledLinks, StyledNav } from './NavbarElements'
import Logo from '../../../../public/chiemsee_gin_logo.svg'
import Helmet from 'react-helmet'

export const Navbar = ({isHome}) => {

  const [isMounted, setIsMounted] = useState(false);
  /* tslint:disable-next-line */
  const scrollDirection = useScrollDirection('down');
  const [scrolledToTop, setScrolledToTop] = useState(true);

  const handleScroll = () => {
    setScrolledToTop(window.pageYOffset < 50);
  };

  useEffect(() => {
    const timeout = setTimeout(() => {
      setIsMounted(true);
    }, 100);

    window.addEventListener('scroll', handleScroll);

    return () => {
      clearTimeout(timeout);
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);


  return (
    <StyledHeader scrollDirection={scrollDirection} scrolledToTop={scrolledToTop}>
      <Helmet>
          <title>Chiemsee Gin</title>
          <meta name="description" content="Generated by Chiemsee Gin Team" />
          <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png" />
          <link rel="manifest" href="favicons/site.webmanifest" />
          <link rel="mask-icon" href="favicons/safari-pinned-tab.svg" color="#5bbad5" />
          <link rel="shortcut icon" href="favicons/favicon.ico" />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="msapplication-config" content="favicons/browserconfig.xml" />
          <meta name="theme-color" content="#fffdfd"></meta>

      </Helmet>
      <StyledNav>
      <Menu />
      <div className="mx-auto md:ml-0" >

          {isHome ? (<LinkScroll to="home"
                      smooth={true}
                      duration={500}
                      spy={true}
                      exact='true'>
                        <a href="/" aria-label="home" >
                          <Logo className="w-16"/>
                        </a></LinkScroll>) : (<Link href="/" aria-label="home">
                        <Logo className="w-16"/>
                    </Link>)}
        </div>
        <StyledLinks>
          <ol>
            {isHome ? (<li><LinkScroll to="premiumgin"
                        smooth={true}
                        duration={500}
                        spy={true}
                        exact='true'>
                          <a href="/" aria-label="premiumgin">
                            Premium Gin
                          </a></LinkScroll></li>):
                    (<li><Link href="/">
                     
                      Premium Gin
                    
                    </Link></li>)}
            <li>
              <Link href="/shop/chiemsee-premium-gin"  >
               
                  Shop
                
              </Link>
            </li>
            <li>
              <Link href="/rezepte">
               
                  Chiemgauer Rezepte
                
              </Link>
            </li>
            <li>
              <Link href="/chiemsee">
                
                  Chiemsee
               
              </Link>
            </li>
            <li>           
              <Link href="/geschichte">
               
                  Geschichte
                
              </Link>
            </li> 
          </ol>
          </StyledLinks>
      </StyledNav>
      <SideCart />
    </StyledHeader>

  )
}

