import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { useQuery, gql } from '@apollo/client';
import  {ALL_RECIPES, RECIPE_INFO, RECIPE_TITLES} from '../../src/apollo_files/queries/recipes';
import { initApollo } from '../../src/apollo_files/apolloClient';


// function Props({title}){
//   const { loading, error, data } = useQuery(RECIPE_INFO, {
//     variables: { title: title }
//   });
//   if (loading) return <p>Loading...</p>;
//   if (error) return <p>Error :(</p>;
//     console.log(data)
//   return (
//     <>
//     props
//     <div>
//      {data.recipe.recipeIngredients}
//     </div>
//     </>
//   )
// }


// function Paths() {
//   const { loading, error, data } = useQuery(RECIPE_TITLES);
//   if (loading) return <p>Loading...</p>;
//   if (error) return <p>Error :(</p>;
//     console.log(data)
//   return (
//     <>
//     paths
//     <div>
//       {data.recipes.map((recipe) => {
     
//         return(
//           <div key={recipe.title}>
//           <p>
//             {recipe.title.split(" ").join("-")}
//           </p>
//           <Props title={recipe.title} />
//         </div>
//         )
        
//       })}
//     </div>
//     </>
//   )
// }





function Recipes() {
  const { loading, error, data } = useQuery(ALL_RECIPES);
  
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
    <>
    {data.recipes.map((recipe) => {
      console.log("recipe", recipe)
      let innerHtml = recipe.recipeInstructions.html
      return (
      <div key={recipe.id}>
        <div>
          <Link href={`recipes/${recipe.title.split(" ").join("-")}`}><a>
            <h1>{recipe.title}</h1>
            </a></Link>
          
          <p>{recipe.recipeIngredients}</p>
        <div dangerouslySetInnerHTML={{ __html: innerHtml }}></div>
        </div>
      </div>
      )
    })}
    </>
    ) 
}



export default function RecipeMain() {
 
  

 
  return (
    <div className="{styles.container}">
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="{styles.main}">
        <Recipes />
        {/* <Paths /> */}
   
      </main>


    </div>
  )
}
