import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { useQuery, gql } from '@apollo/client';
import  {ALL_RECIPES, RECIPE_INFO, RECIPE_TITLES} from '../../src/apollo_files/queries/recipes';
import { initApollo } from '../../src/apollo_files/apolloClient';
import {client as shopifyClient} from '../../src/utils/shopify'

// const ALL_PRODUCTS = gql`

// `



// function Props({title}){
//   const { loading, error, data } = useQuery(RECIPE_INFO, {
//     variables: { title: title }
//   });
//   if (loading) return <p>Loading...</p>;
//   if (error) return <p>Error :(</p>;
//     console.log(data)
//   return (
//     <>
//     props
//     <div>
//      {data.recipe.recipeIngredients}
//     </div>
//     </>
//   )
// }


// function Paths() {
//   const { loading, error, data } = useQuery(RECIPE_TITLES);
//   if (loading) return <p>Loading...</p>;
//   if (error) return <p>Error :(</p>;
//     console.log(data)
//   return (
//     <>
//     paths
//     <div>
//       {data.recipes.map((recipe) => {
     
//         return(
//           <div key={recipe.title}>
//           <p>
//             {recipe.title.split(" ").join("-")}
//           </p>
//           <Props title={recipe.title} />
//         </div>
//         )
        
//       })}
//     </div>
//     </>
//   )
// }





function Product({product}) {
  const {
    id = product.Id,
    title = product.title,
    imageUrl = product.images[0].src
  } = product


  return (
    
    <Link href={`products/${title.split(" ").join("-")}`} key={id}><a>
   <div >
      <p>{title}</p>
      <img src={imageUrl} style={{height: "100px"}} className="mx-auto mt-10" />
     </div>
   </a></Link>

    ) 
}



export default function ProductsMain({products}) {
  console.log(products)

  return (
    <div className="{styles.container}">
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <div className="centered m-auto p-12">
        {products.map(product => {
          return (
            <Product product={product} />
          )
        })}
      
   
      </div>


    </div>
  )
}


export async function getStaticProps() {

  const products = await shopifyClient.product.fetchAll()
 
  
  return { props: { products: JSON.parse(JSON.stringify(products))  } }

}
//: JSON.parse(JSON.stringify(products))