/* eslint-disable @next/next/no-css-tags */
import Helmet from 'react-helmet'
import styles from '../styles/Home.module.css'
import React from 'react'


import { useCheckoutUpdate} from '../src/hooks/useCheckoutId'
import Header from '../src/components/general/header'
import { HomePremiumGin } from '../src/components/general/homeGin'
import Vimeoplayer from '../src/components/general/vimeoplayer'
import Head from 'next/head'


export default function Home() {
  
  const header = {
  path: '/images/headers/fraueninsel_small.jpg',
  pathxs: '/images/headers/fraueninsel_small.jpg',
  pathsm: '/images/headers/fraueninsel_small.jpg',
  pathmd: '/images/headers/fraueninsel_small.jpg',
  pathlg: '/images/headers/fraueninsel_small.jpg',
  pathxl: '/images/headers/fraueninsel_small.jpg',
  path2xl: '/images/headers/fraueninsel_small.jpg',
  title: 'CHIEMSEE GIN',
  subtitle: 'Eine Perle des Genusses direkt vom bayerischen Meer',
  button: 'Zum Premium Gin',
  buttonLink: '/shop/chiemsee-premium-gin'
  }
  
  const [isHome, setIsHome] = React.useState(false)

  const timeout = setTimeout(() => {
    setIsHome(true);
  }, 100);



  const {addId} = useCheckoutUpdate()

  React.useEffect(() => {
    addId()
  }, [addId])
  
  
  
  return (
    <div className={styles.container}>
    
        
        <Helmet>
          <title>Chiemsee Gin</title>
          <meta name="description" content="Generated by Chiemsee Gin Team" />
          <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png" />
          <link rel="manifest" href="favicons/site.webmanifest" />
          <link rel="mask-icon" href="favicons/safari-pinned-tab.svg" color="#5bbad5" />
          <link rel="shortcut icon" href="favicons/favicon.ico" />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="msapplication-config" content="favicons/browserconfig.xml" />
          <meta name="theme-color" content="#223669" />
          <link rel="preconnect" href="https://vitals.vercel-insights.com" />
          <link rel="preconnect" href="https://chiemsee-gin.myshopify.com" />
          {/*  eslint-disable no-eval */ }
          <link rel="preload" as="style" href="/essonnes-display/style.css"/>  
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.woff2"  type="font/woff2" crossOrigin="anonymous"/>
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.woff"  type="font/woff" crossOrigin="anonymous"/>
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.ttf"  type="font/ttf" crossOrigin="anonymous"/>
          
 

      </Helmet>    
      <Head>
      
        <title>Chiemsee Premium Gin</title>
        <meta name="title" content="Chiemsee Premium Gin"/>
        <meta name="description" content="Chiemsee Gin ist der Premium Gin vom Bayerischen Meer. Gin aus Bayern so einzigartig wie seine Heimat - nach Chiemgauer Brenntradition seit 1892." />


        <meta property="og:type" content="Shop"/>
        <meta property="og:url" content="https://www.chiemseegin.de/"/>
        <meta property="og:title" content="Chiemsee Premium Gin"/>
        <meta property="og:description" content="Chiemsee Gin ist der Premium Gin vom Bayerischen Meer. Gin aus Bayern so einzigartig wie seine Heimat - nach Chiemgauer Brenntradition seit 1892." />
        <meta property="og:image" content="https://www.chiemseegin.de/_next/image?url=%2F_next%2Fstatic%2Fimage%2Fpublic%2Fimages%2Fbild_sina_scan_600dpi_dunkel.b420ba87e207135b1a5636506aec18ea.png&w=1200&q=75"/>


        <meta property="twitter:card" content="summary_large_image"/>
        <meta property="twitter:url" content="https://www.chiemseegin.de/"/>
        <meta property="twitter:title" content="Chiemsee Premium Gin"/>
        <meta property="twitter:description" content="Chiemsee Gin ist der Premium Gin vom Bayerischen Meer. Gin aus Bayern so einzigartig wie seine Heimat - nach Chiemgauer Brenntradition seit 1892." />
        <meta property="twitter:image" content="https://www.chiemseegin.de/_next/image?url=%2F_next%2Fstatic%2Fimage%2Fpublic%2Fimages%2Fbild_sina_scan_600dpi_dunkel.b420ba87e207135b1a5636506aec18ea.png&w=1200&q=75"/>

      </Head>
      
      <Header header={header} />
      <main className={styles.main}>
          <section id="home ">
          <h3 className ="text-center my-10 text-2xl" >Ein Chiemgauer Gin so einzigartig wie seine Heimat
</h3>
            <div className="py-8">
              <p className="">Chiemsee Gin ist der Premium Gin vom bayerischen Meer. Unser Wacholderschnaps wird in unserer seit 1829 bestehenden Edelbrandmanufaktur in traditioneller Handarbeit destilliert. Alle Zutaten für unseren Chiemgauer Gin werden mit größter Sorgfalt und mit Blick auf Nachhaltigkeit handverlesen. Ein außergewöhnlicher und facettenreicher Gin von und für seine bayerische Heimat und die Menschen, die diese so sehr lieben.
              Mit jeder verkauften Flasche spenden wir 1 € für den Chiemgauer Naturschutz und unterstützen somit die Erhaltung unserer einzigartigen Heimat.</p>
            </div>
        </section>
      
           <Vimeoplayer />
          <HomePremiumGin />
 
    
          
       
      </main>


    </div>
  )
}

