import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React, { useEffect } from 'react'
import {useCheckout, useCheckoutUpdate} from '../src/hooks/useCheckoutId'
import { useCartContext, useCartUpdateContext } from '../src/hooks/useCartStorage'
import shopifyClient from '../src/utils/shopify'


import { useQuery, gql } from '@apollo/client';


export default function Home() {

  const {cart} = useCartContext()

  const {cartCheckoutInfo, GinId} = useCheckout()


  React.useEffect(() => {
    addId()
  }, [])
  
  const {addId, clearId} = useCheckoutUpdate()
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Chiemsee Gin</title>
        <meta name="description" content="Generated by Chiemsee Gin Team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/recipes">
            recipes
        </Link>
        <br/>
        <br/>
        <Link href="/products">
            products
        </Link>
        
        
    
          
       
      </main>


    </div>
  )
}

