/* eslint-disable @next/next/no-css-tags */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React, { useEffect } from 'react'
import {useCheckout, useCheckoutUpdate} from '../src/hooks/useCheckoutId'
import { useCartContext, useCartUpdateContext } from '../src/hooks/useCartStorage'
import shopifyClient from '../src/utils/shopify'
import Header from '../src/components/general/header'
import ProductImageBG from '../src/components/shop/productImage';
import { useQuery, gql } from '@apollo/client';
import { HomePremiumGin } from '../src/components/general/homeGin'
import { CSSTransition } from 'react-transition-group'
import Helmet from 'react-helmet'


export default function Home() {
  
  const header = {
  path: '/images/backgroundheader.jpg',
  title: 'Willkommen bei Chiemsee Premium Gin',
  subtitle: 'Eine Perle des Genusses direkt aus dem bayrischen Meer',
  button: 'Zum Premium Gin',
  buttonLink: 'chiemsee-premium-gin'
  }
  
  const [isHome, setIsHome] = React.useState(false)

  const timeout = setTimeout(() => {
    setIsHome(true);
  }, 100);



  const {addId} = useCheckoutUpdate()

  React.useEffect(() => {
    addId()
  }, [addId])
  
  
  
  return (
    <div className={styles.container}>
    
        
        <Helmet>
          <title>Chiemsee Gin</title>
          <meta name="description" content="Generated by Chiemsee Gin Team" />
          <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png" />
          <link rel="manifest" href="favicons/site.webmanifest" />
          <link rel="mask-icon" href="favicons/safari-pinned-tab.svg" color="#5bbad5" />
          <link rel="shortcut icon" href="favicons/favicon.ico" />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="msapplication-config" content="favicons/browserconfig.xml" />
          <meta name="theme-color" content="#fffdfd"></meta>
          <link rel="preconnect" href="https://vitals.vercel-insights.com" />
          <link rel="preconnect" href="https://chiemsee-gin.myshopify.com" />
          {/*  eslint-disable no-eval */ }
          <link rel="preload" as="style" href="/essonnes-display/style.css"/>  
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.woff2"  type="font/woff2" crossOrigin="anonymous"/>
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.woff"  type="font/woff" crossOrigin="anonymous"/>
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.ttf"  type="font/ttf" crossOrigin="anonymous"/>
          

      </Helmet>
      
      <Header header={header} />
      <main className={styles.main}>
          <section id="home">
            <div className="">
              <p className="">Chiemsee Gin ist der Premium Gin vom bayerischen Meer – angenehm herb mit frischen
                Noten. Unser Wacholderschnaps wird in der seit 1892 bestehenden Edelbrandmanufaktur
                Guggenbichler in traditioneller Handarbeit mit handverlesenen Zutaten hergestellt. Ein
                außergewöhnlicher und facettenreicher Gin von und für seine bayerische Heimat und die
                Menschen, die sie/diese so sehr lieben. Mit jeder verkauften Flasche wird 1€ für den
                Naturschutz des Chiemgaus &amp; Chiemsees gespendet und somit die Erhaltung unserer
                einzigartigen Heimat unterstützt.
              </p>
            </div>
        </section>
      
          <HomePremiumGin />
 
        <section id="recipe-slider">

        </section>
    
          
       
      </main>


    </div>
  )
}

