import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import {useCheckout, useCheckoutUpdate} from '../src/hooks/useCheckoutId'

import { useQuery, gql } from '@apollo/client';


export default function Home() {

  const {cartCheckoutId} = useCheckout()
  const {addId, clearId} = useCheckoutUpdate()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/recipes">
            recipes
        </Link>
        <br/>
        <Link href="/mainGin">
            Main Gin
        </Link>
        <br/>
        <Link href="/products">
            dynamic products (not implemented)
        </Link>
        
        <div>
          <h2>
            Testing Buttons
          </h2>

          <p>CheckoutId: {cartCheckoutId}</p>

          <button onClick={addId}>
              AddId
          </button>
          <br/>
          <button onClick={clearId}>
              clearId
          </button>
        </div>
      </main>


    </div>
  )
}
