/* eslint-disable @next/next/no-css-tags */
import Helmet from 'react-helmet'
import styles from '../styles/Home.module.css'
import React from 'react'

import { useCheckoutUpdate} from '../src/hooks/useCheckoutId'
import Header from '../src/components/general/header'
import { HomePremiumGin } from '../src/components/general/homeGin'



export default function Home() {
  
  const header = {
  path: '/images/headers/teal-50-crop.jpg',
  pathxs: '/images/headers/teal-50-crop.jpg',
  pathsm: '/images/headers/teal-50-crop.jpg',
  pathmd: '/images/headers/teal-50-medium.jpg',
  pathlg: '/images/headers/teal-50-medium.jpg',
  pathxl: '/images/headers/teal-50-large1.jpg',
  path2xl: '/images/headers/teal-50.jpg',
  title: 'CHIEMSEE GIN',
  subtitle: 'Eine Perle des Genusses direkt vom bayerischen Meer',
  button: 'Zum Premium Gin',
  buttonLink: '/shop/chiemsee-premium-gin'
  }
  
  const [isHome, setIsHome] = React.useState(false)

  const timeout = setTimeout(() => {
    setIsHome(true);
  }, 100);



  const {addId} = useCheckoutUpdate()

  React.useEffect(() => {
    addId()
  }, [addId])
  
  
  
  return (
    <div className={styles.container}>
    
        
        <Helmet>
          <title>Chiemsee Gin</title>
          <meta name="description" content="Generated by Chiemsee Gin Team" />
          <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png" />
          <link rel="manifest" href="favicons/site.webmanifest" />
          <link rel="mask-icon" href="favicons/safari-pinned-tab.svg" color="#5bbad5" />
          <link rel="shortcut icon" href="favicons/favicon.ico" />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="msapplication-config" content="favicons/browserconfig.xml" />
          <meta name="theme-color" content="#223669" />
          <link rel="preconnect" href="https://vitals.vercel-insights.com" />
          <link rel="preconnect" href="https://chiemsee-gin.myshopify.com" />
          {/*  eslint-disable no-eval */ }
          <link rel="preload" as="style" href="/essonnes-display/style.css"/>  
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.woff2"  type="font/woff2" crossOrigin="anonymous"/>
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.woff"  type="font/woff" crossOrigin="anonymous"/>
          <link rel="preload" as="font" href="/essonnes-display/EssonnesDisplay-Regular.ttf"  type="font/ttf" crossOrigin="anonymous"/>
          

      </Helmet>
      
      <Header header={header} />
      <main className={styles.main}>
          <section id="home ">
            <div className="py-8">
              <p className="">Chiemsee Gin ist der Premium Gin vom bayerischen Meer. Unser Wacholderschnaps wird in der seit 1829 bestehenden Edelbrandmanufaktur Guggenbichler in traditioneller Handarbeit destilliert. Alle Zutaten für unseren Gin werden mit größter Sorgfalt und mit Blick auf Nachhaltigkeit handverlesen. Ein außergewöhnlicher und facettenreicher Gin von und für seine bayerische Heimat und die Menschen, die diese so sehr lieben.
              </p>
              <p>Mit jeder verkauften Flasche spenden wir 1 € für den Chiemgauer Naturschutz und unterstützen somit die Erhaltung unserer Einzigartigen Heimat.</p>
            </div>
        </section>
      
          <HomePremiumGin />
 
        <section id="recipe-slider"> 

        </section>
    
          
       
      </main>


    </div>
  )
}

